/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import view.customer.CustomerPanel;
import view.item.ItemPanel;
import view.item.stock.StockPanel;
import view.sales.LedgerQuotationPanel;
import view.sales.SalesPanel;
import view.vendor.VendorPanel;

/**
 *
 * @author Owner
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        tabbedPanel.setSize(screenDimension);
        repaint();
        revalidate();
        initPanels();
    }

    
    private void initPanels(){
       // JPanel pan=new JPanel();
        //pan.setBackground(Color.red);
        //MasterPanel masterPanel=new MasterPanel();
        
        ItemPanel itemPanel=new ItemPanel();
        itemTabPanel.add("Item Panel",itemPanel);
        
        CustomerPanel customerPanel=new CustomerPanel();
        customerTabPanel.add("Customer Panel",customerPanel);
        
        StockPanel stockPanel=new StockPanel();
        stockTabPanel.add("Stock Panel",stockPanel);
        
        SalesPanel salesPanel=new SalesPanel();
        saleTabPanel.add("Sales Panel", salesPanel);
        
        LedgerQuotationPanel ledgerQuotationPanel=new LedgerQuotationPanel();
        ledgerTabPanel.add("Ledger/Quotation",ledgerQuotationPanel);
        
        VendorPanel vendorPanel=new VendorPanel();
        vendorTabPanel.add("Vendor Panel", vendorPanel);
        
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        itemTabPanel = new javax.swing.JTabbedPane();
        customerTabPanel = new javax.swing.JTabbedPane();
        stockTabPanel = new javax.swing.JTabbedPane();
        saleTabPanel = new javax.swing.JTabbedPane();
        ledgerTabPanel = new javax.swing.JTabbedPane();
        reportsTabPanel = new javax.swing.JTabbedPane();
        vendorTabPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPanel.addTab("Item", itemTabPanel);
        tabbedPanel.addTab("Customer", customerTabPanel);
        tabbedPanel.addTab("Stocks", stockTabPanel);
        tabbedPanel.addTab("Sale", saleTabPanel);
        tabbedPanel.addTab("Ledger", ledgerTabPanel);
        tabbedPanel.addTab("Reports", reportsTabPanel);
        tabbedPanel.addTab("Vendor", vendorTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.getAccessibleContext().setAccessibleName("Item");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane customerTabPanel;
    private javax.swing.JTabbedPane itemTabPanel;
    private javax.swing.JTabbedPane ledgerTabPanel;
    private javax.swing.JTabbedPane reportsTabPanel;
    private javax.swing.JTabbedPane saleTabPanel;
    private javax.swing.JTabbedPane stockTabPanel;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTabbedPane vendorTabPanel;
    // End of variables declaration//GEN-END:variables
}
