/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Owner
 */
public class HomeTabbed extends javax.swing.JFrame {

    /**
     * Creates new form HomeTabbed
     */
    public HomeTabbed() {
        initComponents();
        
        JTabbedPane jtbExample = new JTabbedPane();
        JPanel jplInnerPanel1 =createInnerPanel("Tab 2 Contains Icon only");
        jtbExample.addTab("One",jplInnerPanel1);
        jtbExample.setSelectedIndex(0);
        JPanel jplInnerPanel2 = createInnerPanel("Tab 2 Contains Icon only");
        jtbExample.addTab("Two",  jplInnerPanel2);
        JPanel jplInnerPanel3 = createInnerPanel("Tab 3 Contains Tooltip and Icon");
        jtbExample.addTab("Three", jplInnerPanel3);
        JPanel jplInnerPanel4 = createInnerPanel("Tab 4 Contains Text only");
        jtbExample.addTab("Four", jplInnerPanel4);
        // Add the tabbed pane to this panel.
        setLayout(new GridLayout(1, 1));
        add(jtbExample);
        /*frame.getContentPane().add(new JTabbedPaneDemo(),
				BorderLayout.CENTER);
		frame.setSize(400, 125);
		frame.setVisible(true);*/
    }

    protected JPanel createInnerPanel(String text) {
            JPanel jplPanel = new JPanel();
            JLabel jlbDisplay = new JLabel(text);
            jlbDisplay.setHorizontalAlignment(JLabel.CENTER);
            jplPanel.setLayout(new GridLayout(1, 1));
            jplPanel.add(jlbDisplay);
            return jplPanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeTabbed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
