/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.item;

import beans.Item;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.item.ItemClient;

/**
 *
 * @author Owner
 */
public class ViewItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewItemPanel
     */
    public ViewItemPanel() {
        initComponents();
        List<Object> itemList=new ItemClient().get();
        if(itemList.size()>0){
            try{
                DefaultTableModel tableModel=(DefaultTableModel)tableItems.getModel();
                tableModel.setRowCount(itemList.size());
                tableItems.setModel(tableModel);
                int row=0;
                for(Object itemObject:itemList){
                    Item item=(Item)itemObject;
                    tableItems.setValueAt(item.getId(), row, 0);
                    tableItems.setValueAt(item.getName(), row, 1);
                    tableItems.setValueAt(item.getPurchasePrice(), row, 2);
                    tableItems.setValueAt(item.getSalePrice(), row, 3);
                    tableItems.setValueAt(item.getVat(), row, 4);
                    tableItems.setValueAt(item.getDiscount(), row, 5);
                    row++;
                }
                tableItems.revalidate();
                tableItems.repaint();
            }catch(Exception e){
                e.printStackTrace();
            }   
        }
        
        
    }

    
    public JTable getTable(){
        return tableItems;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        tableItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableItems.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Name", "Purchase Price", "Sale Price", "VAT", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItems.setRowHeight(25);
        jScrollPane1.setViewportView(tableItems);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Item List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItems;
    // End of variables declaration//GEN-END:variables
}
