/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.item.stock;

import beans.Item;
import beans.Stock;
import java.util.List;
import javax.swing.JOptionPane;
import services.item.ItemClient;
import services.item.stocks.StockClient;

/**
 *
 * @author Owner
 */
public class AddStockPanel extends javax.swing.JPanel {

    private List<Object> itemList;
    Stock stock;
    /**
     * Creates new form AddStocks
     */
    public AddStockPanel() {
        initComponents();
        itemList=new ItemClient().get();
        //comboItemNames.removeActionListener(comboItemNames);
        comboItemNames.removeAllItems();
        for(Object itemObject:itemList){
            Item item=(Item)itemObject;
            comboItemNames.addItem(item.getName());
        }
        //comboItemNames.addActionListener(comboItemNames);
        repaint();
        revalidate();
    }

    private Integer getItemId(String itemName){
        for(Object itemObject:itemList){
            Item item=(Item)itemObject;
            if(item.getName().equalsIgnoreCase(itemName))
                return item.getId();
        }
        return 0;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textAvailable = new javax.swing.JTextField();
        textNewStock = new javax.swing.JTextField();
        comboItemNames = new javax.swing.JComboBox<>();
        buttonAddStock = new javax.swing.JButton();
        textItemCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Stocks");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Available Stock");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("New Stock");

        textAvailable.setEditable(false);

        comboItemNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboItemNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemNamesActionPerformed(evt);
            }
        });

        buttonAddStock.setText("Add To Stock");
        buttonAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStockActionPerformed(evt);
            }
        });

        textItemCode.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Item Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(buttonAddStock))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboItemNames, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboItemNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(buttonAddStock)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboItemNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemNamesActionPerformed
       // JOptionPane.showMessageDialog(null, "Changed");
       if(comboItemNames.getSelectedItem()!=null){
            String itemName=comboItemNames.getSelectedItem().toString();
            
            Integer itemId=getItemId(itemName);
            System.out.println("item id : "+itemId);
            if(itemId>0){
                stock=(Stock)new StockClient().getByID(itemId);
                if(stock!=null){
                    textAvailable.setText(stock.getAvailableStock().toString());
                    textItemCode.setText(stock.getItemId().toString());
                }else{
                    textAvailable.setText("0");
                    textItemCode.setText(itemId.toString());
                }
            }
       }
    }//GEN-LAST:event_comboItemNamesActionPerformed

    private void buttonAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStockActionPerformed
        if(textNewStock.getText()!=null && !textNewStock.getText().equalsIgnoreCase(" ")){
            Integer newStockQuantity=Integer.parseInt(textNewStock.getText());
            Stock newStock=new Stock();
            newStock.setItemId(Integer.parseInt(textItemCode.getText()));
            newStock.setAvailableStock(newStockQuantity);
            Integer stockQty = new StockClient().add(newStock);
            System.out.println(stockQty);
            if(stockQty==(newStockQuantity+Integer.parseInt(textAvailable.getText()))){
                JOptionPane.showMessageDialog(null, "Stock has been added successfully ");
                textNewStock.setText("");
                textAvailable.setText(stockQty.toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Stock upadate operation failed");
            }
        }
    }//GEN-LAST:event_buttonAddStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddStock;
    private javax.swing.JComboBox<String> comboItemNames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textAvailable;
    private javax.swing.JTextField textItemCode;
    private javax.swing.JTextField textNewStock;
    // End of variables declaration//GEN-END:variables
}
